config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about"
  resources :books,only:[:create,:index,:show,:edit,:update,:destroy] do
    resource :favorite,only:[:create,:destroy]
    resources :book_comments,only:[:create,:destroy]
  end
  resources :users,only:[:index,:show,:edit,:update] do
    resource :relationship, only:[:create,:destroy]
    get :followings, on: :member
    get :followers, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title,presence: true
  validates :body,presence: true, length: {maximum: 200}
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment,presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:name]
         
  has_many :books, dependent: :destroy
  validates :name, uniqueness: true,length: {minimum: 2,maximum: 20}
  validates :introduction, length: {maximum: 50}
  attachment :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :relationships, foreign_key: :follower_id, dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  def is_followed_by?(user)
    reverse_of_relationships.find_by(follower_id: user.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
 
  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    #devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book.id)
  end
  
  def destroy
    BookComment.find_by(id: params[:id],book_id: params[:book_id]).destroy
    redirect_to request.referer || root_path
  end
  
  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id),notice: "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end
  
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end
  
  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end
  
  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end
  
  def update
   @book = Book.find(params[:id])
   if @book.update(book_params)
     redirect_to book_path(@book),notice: "You have updated book successfully."
   else
     render :edit
   end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book_id = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book_id.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    book_id = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book_id.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  def create
    following = current_user.relationships.build(followed_id: params[:user_id])
    following.save
    redirect_to request.referer || root_path
  end
  
  def destroy
    following = current_user.relationships.find_by(followed_id: params[:user_id])
    following.destroy
    redirect_to request.referer || root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end
  
  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user),notice: "You have updated user successfully."
    else
      render :edit
    end
  end
  
  def followings
    user = User.find(params[:id])
    @user = user.followings
  end
  
  def followers
    user = User.find(params[:id])
    @user = user.followers
  end
  
  
  private
  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-ma-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      
      <div id="error_explanation">
      <% if @book.errors.any? %>
      <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
      </div>
      
      <%= form_with model: @book, local: true do |f|%>
        <div class="form-group">
          <label for="book_title">Title</label>
          <div><%= f.text_field :title,size: 50 %></div>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <div><%= f.text_area :body,size: "50x2" %></div>
        </div>
        <div class="form-group">
          <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book" style="user-select: auto;">
        </div>
      <% end %>
      <%= link_to "Show",book_path(@book)%>
      |
      <%= link_to "Back",books_path%>
      
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id=notice></p>
<div class="container px-5 px-sm-0">
  
  <div id="error_explanation">
  <% if @book.errors.any? %>
  <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
  </div>
  
  <div class="row">
    
    
    <%= render "users/userinfo",user: @user,book: @book %>
    
    
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            
            <td>
            <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image,:fill,10,10, format: "jpeg",fallback: "images/no_image.jpg"%>
            <% end %>
            </td>
            
            <td><%= link_to book.title,book_path(book.id) %></td>
            <td><%= book.body %></td>
            
            <% if book.favorited_by?(current_user)%> 
              <td>
                <%= link_to book_favorite_path(book),method: :delete do %>
                <i class = "fas fa-heart"></i><%= book.favorites.count %>
                <% end %>
              </td>
            <% else %>
              <td>
              <%= link_to book_favorite_path(book),method: :post do %>
              <i class = "far fa-heart"></i><%= book.favorites.count %>
              <% end %>
              </td>
            <% end %>
            <td>コメント数: <%= book.book_comments.count %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    
    
    
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    
    
    <%= render 'users/userinfo',user: @user,book: @book_new %>
    
    
    
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user.id) do %>
              <%= attachment_image_tag @book.user, :profile_image,:fill,10,10, format: "jpeg",fallback: "images/no_image.jpg"%>
              <br>
              <%= @book.user.name %>
              <% end %>
            </td>
            <td><%= link_to @book.title, book_path(@book) %></td>
            <td><%= @book.body %></td>
            <% if @book.favorited_by?(current_user)%> 
            <td>
              <%= link_to book_favorite_path(@book),method: :delete do %>
              <i class = "fas fa-heart"></i><%= @book.favorites.count %> 
              <% end %>
            </td>
            <% else %>
            <td>
              <%= link_to book_favorite_path(@book),method: :post do %>
              <i class = "far fa-heart"></i><%= @book.favorites.count %> 
              <% end %>
            </td>
            <% end %>
            
            <td>コメント数: <%= @book.book_comments.count %></td>
            
            <% if current_user.id == @book.user_id %>
              <td>
                <%=link_to "Edit", edit_book_path(@book.id),class: "btn btn-sm btn-success" %>
              </td>
              <td>
                <%= link_to "Destroy" ,book_path(@book.id),method: :delete, class: "btn btn-sm btn-danger","data-confirm" => "本当に削除しますか？" %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      
      <% @book.book_comments.each do |book_comment| %>
        <table>
          <tbody>
            <td>
              <%= link_to user_path(book_comment.user.id) do %>
                <%= attachment_image_tag book_comment.user, :profile_image,:fill,10,10, format: "jpeg",fallback: "images/no_image.jpg"%>
                <br>
                <%= book_comment.user.name %>
              <% end %>
            </td>
            <td>
              <%= book_comment.comment %>
            </td>
            <td>
              <% if book_comment.user == current_user %>
                <%= link_to "Destroy", book_book_comment_path(book_comment.book_id,book_comment), method: :delete, class: "btn btn-sm btn-danger" %>
              <% end %>
            </td>
          </tbody>
        </table>
      <% end %>
      
      
      <div>
        <%= form_with(model:[@book,@book_comment],local: true) do |f| %>
        <div class="form-group">
          <%= f.text_area :comment, size: "100x6" %>
        </div>
        <div>
          <%= f.submit "送信" %>
        </div>
        <% end %>
      </div>
    </div>
    
    
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>
                welcome to
                <i class="fas fa-book"></i><strong>Bookers</strong>
                !!
            </h1>
            <p>
                In
                <i class="fas fa-book"></i><strong>Bookers</strong>,
            </p>
            <p>
                you can share and exchange your opinions , inpressions , and emotions
            </p>
            <p>
                about various books!
            </p>
            <div class="btn-wrapper col-10 mx-auto">
                <div class="row">
                    <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
                </div>
                <div class="row">
                    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/7d6d903ecb.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
              <i class="fas fa-home"> Home</i>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path,class: 'nav-link text-light' do  %>
              <i class="fas fa-users"> Users</i>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: 'nav-link text-light' do  %>
              <i class="fas fa-book-open"> Books</i>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"> logout</i>
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-light' do %>
              <i class="fas fa-home"> Home</i>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to home_about_path, class: 'nav-link text-light' do %>
              <i class="fas fa-link"> About</i>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"> sign up</i>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"> login</i>
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
    <%= yield %>
    </main>
    <footer class="bg-white text-brack">
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_userinfo.html.erb
 <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image,:fill,100,100, format: "jpeg",fallback: "images/no_image.jpg"%>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <td><%= link_to user.followings.count, followings_user_path(user) %></td>
          </tr>
          <tr>
            <th>followers</th>
            <td><%= link_to user.followers.count, followers_user_path(user) %></td>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <% if user.id == current_user.id %>
          <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do  %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        <% else %>
          <% if user.is_followed_by?(current_user) %>
            <%= link_to user_relationship_path(user),method: :delete do%>
              <button class = "btn btn-danger">フォロー外す</button>
            <% end %>
          <% else %>
            <%= link_to user_relationship_path(user),method: :post do%>
              <button class = "btn btn-success">フォローする</button>
            <% end %>
          <% end %>
        <% end %>
      </div>
      
      
      <h2 class="mt-3">New book</h2>
      <%= form_with model: book, local: true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <div><%= f.text_field :title %></div>
        </div>
        <div class="form-group">
          <label for="book_body">Opinion</label>
          <div><%= f.text_area :body %></div>
        </div>
        <div class="form-group">
          <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book"></input>
        </div>
      <% end %>
    </div>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-ma-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>User info</h1>
      
      <div id="error_explanation">
      <% if @user.errors.any? %>
      <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
      </div>
      
      <%= form_with model: @user, local: true do |f|%>
        <div class="form-group">
          <label for="book_title">Name</label>
          <div><%= f.text_field :name,size: 50 %></div>
        </div>
        <div class="form-group">
        <label for="book_title">Image</label>
        <div><%= f.attachment_field :profile_image %></div>
        </div>
        <div class="form-group">
          <label for="book_opinion">Introduction</label>
          <div><%= f.text_area :introduction,size: "50x2" %></div>
        </div>
        <div class="form-group">
          <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">
        </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    
    <div class="col-md offset-md-1">
      <h2>Follower User</h2>
        <% if @user.present? %>
          <table class="table">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
            <% @user.each do |user| %>
              <tr>
                <td>
                <%= attachment_image_tag user, :profile_image,:fill,20,20, format: "jpeg",fallback: "images/no_image.jpg"%>
                </td>
                <td><%= user.name %></td>
                <td>フォロー数: <%= user.followings.count %></td>
                <td>フォロワー数: <%= user.followers.count %></td>
                <% if user != current_user %>
                  <td>
                    <% if user.is_followed_by?(current_user) %>
                    <%= link_to "フォロー外す", user_relationship_path(user),method: :delete %>
                    <% else %>
                    <%= link_to "フォローする", user_relationship_path(user),method: :post %>
                    <% end %>
                  </td>
                <% end %>
                <td><%= link_to "Show",user_path(user) %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        <% else %>
          <p>フォローされているユーザーはいません</p>
        <% end %>
    </div>
    
  </div>
</div>

app/views/users/followings.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    
    <div class="col-md offset-md-1">
      <h2>Follow User</h2>
        <% if @user.present? %>
          <table class="table">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
            <% @user.each do |user| %>
              <tr>
                <td>
                <%= attachment_image_tag user, :profile_image,:fill,20,20, format: "jpeg",fallback: "images/no_image.jpg"%>
                </td>
                <td><%= user.name %></td>
                <td>フォロー数: <%= user.followings.count %></td>
                <td>フォロワー数: <%= user.followers.count %></td>
                <% if user != current_user %>
                  <td>
                    <% if user.is_followed_by?(current_user) %>
                    <%= link_to "フォロー外す", user_relationship_path(user),method: :delete %>
                    <% else %>
                    <%= link_to "フォローする", user_relationship_path(user),method: :post %>
                    <% end %>
                  </td>
                <% end %>
                <td><%= link_to "Show",user_path(user) %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        <% else %>
          <p>フォローしているユーザーはいません</p>
        <% end %>
    </div>
    
  </div>
</div>

app/views/users/index.html.erb
<p id=notice></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    
    <%= render 'users/userinfo',user: @user,book: @book %>
    
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
            <%= attachment_image_tag user, :profile_image,:fill,20,20, format: "jpeg",fallback: "images/no_image.jpg"%>
            </td>
            <td><%= user.name %></td>
            <td>フォロー数: <%= user.followings.count %></td>
            <td>フォロワー数: <%= user.followers.count %></td>
            <% if user == current_user %>
              <td></td>
            <% else %>
              <td>
                <% if user.is_followed_by?(current_user) %>
                <%= link_to "フォロー外す", user_relationship_path(user),method: :delete %>
                <% else %>
                <%= link_to "フォローする", user_relationship_path(user),method: :post %>
                <% end %>
              </td>
            <% end %>
            <td><%= link_to "Show",user_path(user) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    
    <%= render 'users/userinfo',user: @user,book: @book %>
    
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
            <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image,:fill,40,40, format: "jpeg",fallback: "images/no_image.jpg"%>
            <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
            <td>コメント数: <%= book.book_comments.count %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    
    
  </div>
</div>